services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3223"
      POSTGRES_DB: ecommerce
    ports:
      - "3307:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "3308:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: ecommerce-springboot-server
    volumes:
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "3223"
      REDIS_ADDRESS: redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/pom.xml

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: ecommerce-nextjs-client
    ports:
      - "3000:3000"
    environment:
      SPRING_API_URL: http://backend:8080/abtechzone
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./client/package.json

volumes:
  postgres_data:
    external: true
  maven_cache:
  redis_data:
