services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3307:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "3308:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: ecommerce-springboot-server
    volumes:
      - ./server/src:/app/src
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/pom.xml

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: ecommerce-nextjs-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      SPRING_API_URL: http://backend:8080/abtechzone
      NEXT_PUBLIC_SPRING_API_URL: ${NEXT_PUBLIC_SPRING_API_URL}
      WATCHPACK_POLLING: "true"
    tty: true
    stdin_open: true
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/package-lock.json

volumes:
  postgres_data:
    external: true
  maven_cache:
  redis_data:
