-- Commerce-15 additive upgrade from the accepted Commerce-14 payment schema.
-- Apply while the application is stopped. Never resets Orders, Payments or inventory.
BEGIN;
ALTER TABLE payment
    ADD COLUMN IF NOT EXISTS merchant_request_id varchar(50),
    ADD COLUMN IF NOT EXISTS provider_checkout_id varchar(150),
    ADD COLUMN IF NOT EXISTS checkout_url varchar(2048),
    ADD COLUMN IF NOT EXISTS payment_deadline timestamptz,
    ADD COLUMN IF NOT EXISTS initiation_state varchar(20),
    ADD COLUMN IF NOT EXISTS application_status varchar(20),
    ADD COLUMN IF NOT EXISTS review_reason varchar(100),
    ADD COLUMN IF NOT EXISTS applied_order_id bigint,
    ADD COLUMN IF NOT EXISTS next_query_at timestamptz,
    ADD COLUMN IF NOT EXISTS query_count integer,
    ADD COLUMN IF NOT EXISTS lease_until timestamptz,
    ADD COLUMN IF NOT EXISTS lease_token varchar(36),
    ADD COLUMN IF NOT EXISTS client_ip varchar(45);

-- Hibernate's old generated enum check names vary. Replace only method/provider
-- enum checks, not the separate amount, transaction reference or paid_at guards.
DO $$
DECLARE enum_check record;
BEGIN
    FOR enum_check IN SELECT conname FROM pg_constraint
        WHERE conrelid = 'payment'::regclass AND contype = 'c'
        AND pg_get_constraintdef(oid) ~ '(^|[^a-z_])(method|provider)([^a-z_]|$)'
    LOOP
        EXECUTE format('ALTER TABLE payment DROP CONSTRAINT %I', enum_check.conname);
    END LOOP;
END $$;
ALTER TABLE payment ADD CONSTRAINT ck_payment_method CHECK (method IN ('COD', 'MOCK', 'ONLINE'));
ALTER TABLE payment ADD CONSTRAINT ck_payment_provider CHECK (provider IN ('INTERNAL', 'MOCK', 'MOMO', 'VNPAY', 'PAYOS'));
ALTER TABLE payment DROP CONSTRAINT IF EXISTS ck_payment_application;
ALTER TABLE payment ADD CONSTRAINT ck_payment_application CHECK (
    applied_order_id IS NULL OR (applied_order_id = order_id AND status = 'SUCCEEDED'
        AND application_status IS NOT NULL AND application_status = 'APPLIED'));
CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_merchant_request ON payment(merchant_request_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_applied_order ON payment(applied_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_next_query ON payment(next_query_at, id);
CREATE INDEX IF NOT EXISTS idx_payment_deadline ON payment(payment_deadline, id);
CREATE TABLE IF NOT EXISTS payment_checkout_key (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    request_key varchar(36) NOT NULL,
    payment_id bigint NOT NULL REFERENCES payment(id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_checkout_key UNIQUE(order_id, request_key)
);
COMMIT;
