server:
  port: 8080
  servlet:
    context-path: /abtechzone

spring:
  application:
    name: ABTechZone
  datasource:
    url: "jdbc:postgresql://localhost:3307/ecommerce"
    username: postgres
    password: 3223
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "c1a82dd9443f07d5dc82ed097662030773c7f2ead8baa97fcfa0dba99f96407a"
  valid-duration: 86400 # in second
  refreshable-duration: 259200 #seconds
