jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 86400 # in second
  refreshable-duration: 259200 #seconds

app:
  swagger:
    enabled: ${SWAGGER_ENABLED:false}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:}

