import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { OrderDetailResponse } from "@/features/orders/order.type";
import { AdminOrderStatusBadge } from "./AdminOrderStatusBadge";
import { AdminOrderStatusActions } from "./AdminOrderStatusActions";
import { formatAdminDate, formatAdminMoney } from "../utils/admin-order.utils";

export function AdminOrderDetailView({ order }: { order: OrderDetailResponse }) {
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><Button render={<Link href="/admin/orders" />} variant="ghost">← Danh sách</Button><h1 className="text-2xl font-semibold">Đơn {order.orderCode}</h1><p className="text-sm text-muted-foreground">Tạo lúc {formatAdminDate(order.createdAt)}</p></div><AdminOrderStatusBadge status={order.status} /></div><AdminOrderStatusActions orderCode={order.orderCode} allowedTransitions={order.allowedTransitions} /><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Thông tin nhận hàng</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><p><strong>{order.recipientName}</strong> · {order.phone}</p><p>{order.fullAddress}</p></CardContent></Card><Card><CardHeader><CardTitle>Thanh toán</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><p>Phương thức: {order.paymentMethod}</p><p>Trạng thái: {order.paymentStatus}</p><p>Tạm tính: {formatAdminMoney(order.subtotalAmount)}</p><p>Phí giao: {formatAdminMoney(order.shippingFee)}</p><p>Giảm giá: {formatAdminMoney(order.discountAmount)}{order.voucherCode ? ` · ${order.voucherCode}` : ""}</p><p className="font-semibold">Tổng: {formatAdminMoney(order.totalAmount)}</p></CardContent></Card></div><Card><CardHeader><CardTitle>Sản phẩm ({order.items.length})</CardTitle></CardHeader><CardContent className="space-y-3">{order.items.map((item) => <div key={item.skuId} className="flex justify-between gap-4 border-b pb-2 text-sm last:border-0"><span>{item.productName} × {item.quantity}</span><span>{formatAdminMoney(item.lineTotal)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Lịch sử trạng thái</CardTitle></CardHeader><CardContent className="space-y-3">{order.history.length ? order.history.map((entry, index) => <div key={`${entry.createdAt}-${index}`} className="border-l-2 pl-3 text-sm"><p className="font-medium">{entry.fromStatus || "—"} → {entry.toStatus || entry.status || "—"}</p><p className="text-muted-foreground">{formatAdminDate(entry.createdAt)} · {entry.actorType || "Hệ thống"}{entry.note ? ` · ${entry.note}` : ""}</p></div>) : <p className="text-sm text-muted-foreground">Chưa có lịch sử.</p>}</CardContent></Card></div>;
}
